version: '3.8'

services:
#  KeyCloak Docker Compose Config
  keycloak:
    image: aniruddhadev/key-clock-spi-service:latest  # <-- built with Jib including SPI JAR
    pull_policy: always #This will fetch the latest image every time without cache issue in docker
    platform: linux/amd64
    container_name: keycloak
    restart: unless-stopped
    command: start-dev
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql-e6196a5-aniruddhamukherjee232-bf03.a.aivencloud.com:22667/keyclock?verifyServerCertificate=false&useSSL=true&requireSSL=true
      KC_DB_USERNAME: avnadmin
      KC_DB_PASSWORD: AVNS_F2PWGC2rm-SVNNr8RiC
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: INFO
      KC_EVENTS_LISTENERS: jboss-logging,EXTERNAL_DB_SYNC
      KC_EVENTS_ENABLED: "true"
      KC_SPI_EVENTS_LISTENER_EXTERNAL_DB_SYNC_ENABLED: "true"
#      KEYCLOAK_EXTRA_ARGS: -Dkeycloak.spi.eventListener.providers=EXTERNAL_DB_SYNC
    ports:
      - "8181:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - keycloak_logs:/opt/keycloak/logs
#      - ./key-clock-spi-service/target/key-clock-spi-service.jar:/opt/keycloak/providers/key-clock-spi-service.jar

    networks:
      - backend

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - backend

  # Eureka Server (Optional)
  discovery-service:
    image: aniruddhadev/service-discovery:latest
    pull_policy: always #This will fetch the latest image every time without cache issue in docker
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    depends_on:
      - zipkin
      - keycloak

  api-gateway:
    image: aniruddhadev/api-gateway:latest
    pull_policy: always #This will fetch the latest image every time without cache issue in docker
    container_name: api-gateway
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    depends_on:
      - zipkin
      - discovery-service
      - keycloak
    restart: unless-stopped

  user-service:
    image: aniruddhadev/user-service:latest
    pull_policy: always
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    depends_on:
      - api-gateway
    restart: unless-stopped

volumes:
  keycloak_data:
  keycloak_logs:

networks:
  backend:
    driver: bridge