spring.application.name=scheduler-service
server.port=8081

eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka


#actuator configuration
management.endpoints.web.exposure.include= *
management.endpoint.health.show-details=always


#zipkin
#management.tracing.sampling.probability=1.0

# Enable tracing
management.tracing.enabled=true

# Set the sampling probability (1.0 = 100%)
management.tracing.sampling.probability=1.0

# Send traces to Zipkin
management.zipkin.tracing.enabled=true
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans


#Gamil Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aniruddhamukherjee232@gmail.com
spring.mail.password=zeaw btox xzxf yqmb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=aniruddhamukherjee232@gmail.com

#Kafka Config
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=habit-consumer-group