spring.application.name=habit-service
spring.data.mongodb.uri=mongodb+srv://aniruddha:XhT3FNp0iI87S9XD@cluster0.ytdhejb.mongodb.net/habitservice?retryWrites=true&w=majority
spring.data.mongodb.connection-pool-size=10
spring.data.mongodb.socket-timeout=2000
server.port=8080

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

#actuator configuration
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include= *
management.endpoint.health.show-details=always

#resilience4j configuration
resilience4j.circuitbreaker.instances.inventory.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventory.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.inventory.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.inventory.slidingWindowSize=5
resilience4j.circuitbreaker.instances.inventory.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventory.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.inventory.permittedNumberOfCallsInHalfOpenState=5
resilience4j.circuitbreaker.instances.inventory.automaticTransitionFromOpenToHalfOpenEnabled=true

#zipkin
management.tracing.sampling.probability=1.0